project_id = "ukjpxeptefznpwduwled"

[functions.proxy-page]
verify_jwt = false

[functions.create-step]
verify_jwt = false

[functions.get-configuration]
verify_jwt = false

[functions.serve-widget]
verify_jwt = false

[functions.save-progress]
verify_jwt = false
